In [2]:
#Import the Numpy package under the name np

import numpy as np


In [3]:
#Create a null vector of size 10
Z =np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#Create a null vector of size 10 but the fifth value which is 1
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#Create a vector with values ranging from 10 to 49
y = np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# Reverse a vector (the first element becomes last)
k =np.arange(20)
k =k[::-1]
print(k)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [7]:
#Create a 3x3 matrix with values ranging from 0 to 8
h = np.arange(9).reshape(3,3)
print(h)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Find indices of non­zero elements from [1,2,0,0,4,0]
nonZero = np.nonzero([1,2,0,0,4,0])
print(nonZero)

(array([0, 1, 4]),)


In [9]:
#Create a 3x3x3 array with random values
p=np.random.random((3,3,3))
print(p)

[[[0.13891691 0.58503216 0.26145072]
  [0.29506374 0.6922291  0.18731184]
  [0.49189644 0.19904038 0.3083145 ]]

 [[0.26497228 0.09733076 0.97949925]
  [0.19673609 0.97407295 0.21951674]
  [0.10716201 0.49161073 0.99872415]]

 [[0.1713296  0.89689349 0.73758462]
  [0.27645538 0.24728222 0.51110391]
  [0.96175901 0.43901322 0.34912572]]]


In [10]:
#Create a random vector of size 30 and find the mean value
n = np.random.random(30)
m = n.mean()
print(m)

0.4745793058943453


In [11]:
#Create a 2d array with 1 on the border and 0 inside
l =np.ones((5,5))
l[1:-1,1:-1] =0
print(l)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
#Create an 8x8 matrix and fill it with a checkerboard pattern
r =np.zeros((8,8),dtype=int)
r[1::2,::2] =1
r[::2,1::2] =1
print(r)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [13]:
#What is the major difference between sets, lists, tuples and dictionaries?
print('Lists and tuples are standard Python data types that store values in a sequence. Sets are another standard Python data type that also store values. The major difference is that sets, unlike lists or tuples, cannot have multiple occurrences of the same element and store unordered values.')

Lists and tuples are standard Python data types that store values in a sequence. Sets are another standard Python data type that also store values. The major difference is that sets, unlike lists or tuples, cannot have multiple occurrences of the same element and store unordered values.


In [14]:
#Print first 10 natural numbers using while loop
i=1
while ( i <= 10):
    print (i)
    i = i + 1

1
2
3
4
5
6
7
8
9
10


In [15]:
#Print the numbers -10 to -1 using for loop.
for j in range(-10,0):
    print(j)
    j=j+1


-10
-9
-8
-7
-6
-5
-4
-3
-2
-1


In [16]:
#Print the message “Done” after successful execution of any for a loop.
for g in range(10):
    print (g)
print('Done')

0
1
2
3
4
5
6
7
8
9
Done


In [17]:
#Create a random vector of size 10 and sort it
randomVector= np.random.random(10)
randomVector.sort()
print(randomVector)

[0.00625779 0.0489258  0.16100736 0.22907586 0.53225409 0.62163646
 0.75949228 0.85515902 0.89946737 0.93822773]


In [18]:
#Execute any three math functions using Num
import math

In [19]:
math.sin(3.14159)

2.65358979335273e-06

In [20]:
math.sqrt(9)

3.0

In [21]:
math.log(1)

0.0

In [22]:
math.exp(5)

148.4131591025766